name: DevSecOps CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: "18"

    - name: Install deps
      run: npm install
    
    - name: Run tests
      run: echo "No tests yet"

    - name: Build Docker
      run: docker build -t app .
    - name: Install Trivy
      run: |
        sudo apt-get install -y wget
        wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.53.0_Linux-64bit.deb
        sudo dpkg -i trivy_0.53.0_Linux-64bit.deb

    - name: Scan Docker image
      run: trivy image app
