name: DevSecOps CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: "18"

    - name: Install deps
      run: npm install
    
    - name: Run tests
      run: echo "No tests yet"

    - name: Build Docker
      run: docker build -t app .
    - name: Install Trivy
      run: |
        sudo apt-get install -y wget
        wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.53.0_Linux-64bit.deb
        sudo dpkg -i trivy_0.53.0_Linux-64bit.deb

    - name: Scan Docker image
      run: trivy image app
  zap-scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Start Application
        run: |
          docker run -d -p 3000:3000 ai-ml-devops-app
        # Wait for app to start
      - name: Wait for app
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:3000 > /dev/null; then
              echo "App is up"
              exit 0
            fi
            echo "Waiting..."
            sleep 3
          done
          echo "App did not start"
          exit 1

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: "http://localhost:3000"
  dependency-scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run npm audit
        run: npm audit --audit-level=moderate || true
